// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEtKOkPEuOQqUrPHs9XulWiSC6m2Upbmc',
    appId: '1:727360606263:web:52c11d8a5ddd2670e2efb2',
    messagingSenderId: '727360606263',
    projectId: 'chat-app-19-fb236',
    authDomain: 'chat-app-19-fb236.firebaseapp.com',
    storageBucket: 'chat-app-19-fb236.appspot.com',
    measurementId: 'G-XZR5EY8Z2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcXf1WeH8xDthjVgsAv9ecMTfacL8JW0',
    appId: '1:727360606263:android:d1fd01478b6cafc0e2efb2',
    messagingSenderId: '727360606263',
    projectId: 'chat-app-19-fb236',
    storageBucket: 'chat-app-19-fb236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXr6x48NUAbJRD4C8vvNr3Ktrgc-7Tkw',
    appId: '1:727360606263:ios:fd8573361b1ba33ee2efb2',
    messagingSenderId: '727360606263',
    projectId: 'chat-app-19-fb236',
    storageBucket: 'chat-app-19-fb236.appspot.com',
    iosBundleId: 'com.example.flutterApplication42ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXr6x48NUAbJRD4C8vvNr3Ktrgc-7Tkw',
    appId: '1:727360606263:ios:fd8573361b1ba33ee2efb2',
    messagingSenderId: '727360606263',
    projectId: 'chat-app-19-fb236',
    storageBucket: 'chat-app-19-fb236.appspot.com',
    iosBundleId: 'com.example.flutterApplication42ChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEtKOkPEuOQqUrPHs9XulWiSC6m2Upbmc',
    appId: '1:727360606263:web:94b2cdbcb353246fe2efb2',
    messagingSenderId: '727360606263',
    projectId: 'chat-app-19-fb236',
    authDomain: 'chat-app-19-fb236.firebaseapp.com',
    storageBucket: 'chat-app-19-fb236.appspot.com',
    measurementId: 'G-6SR9CTBN0G',
  );
}
